### ISSUE TITLE
Add link to Learn - > Videos (Advisory Council Presentation/Demo)

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#61]
Add link to Learn - > Videos (top bullet)

BioData Catalyst Presentation & Demo (begins at 1:02:53)
https://videocast.nih.gov/watch=37703

Alt text -> BioData Catalyst Presentation & Demo at National Heart, Lung, and Blood Advisory Council Meeting (begins at 1:02:53)

**Comment by mbwatson** [comment]
we probably shouldn't put so much text here, as it doesn't play nice with the layout. see the screenshot:

![Screenshot from 2020-07-02 10-46-57](https://user-images.githubusercontent.com/6019870/86373420-628cf800-bc51-11ea-9708-124ec6358a30.png)

**Comment by mbwatson** [comment]
this isn't actually the first time the Learn page's layout was pushed because of a biodata catalyst entry. see also the Documentation card here:

![Screenshot from 2020-07-02 11-13-49](https://user-images.githubusercontent.com/6019870/86376607-3ecbb100-bc55-11ea-894f-f19c39d48353.png)

@libcce i wonder if there's a better way to showcase biodata catalyst learn resources separately from the platforms. now that i think of it, managing content would be easier that way. i can think about mocking up a redesign to address this if you think it's worth doing.

**Comment by libcce** [comment]
Yes, I think it is worth revisiting. We have a lot of priorities coming. Let's talk but we will have to respond to the other priorities first. Just need to confirm in Comms. 

Regarding this issue, I suggest shortening to "BioData Catalyst Demonstration (1:02:53)".

Let's try that?
